# Generated by Django 3.0.6 on 2020-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphone',
            name='token',
            field=models.CharField(default=None, max_length=48),
        ),
    ]
