# Generated by Django 3.0.6 on 2020-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signSystem', '0002_userphone_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='token',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
